In [1]:
import pandas as pd
import numpy as np

In [2]:
dpt=pd.read_excel(r'E:\TAOR\Data\2024-5 DPT Data.xlsx')
dpt.head()

,Programme Code,ProgYear,Programme Name,Programme School Name,Programme College,Programme Year,Collection Code,Collection Name,Collection Sequence,Collection Min Value,...,Collection Reg Group,Collection Group Min,Collection Group Max,Collection Operand,Course Code,Course Name,SCQF Credits,Session,Compulsory/Optional,Collection Note
0,PRMSCMGMNT1F,PRMSCMGMNT1F1,Management (MSc by Research),Business School,HSS,1,PGSP11016,Research Skills in the Social Sciences: Data C...,1,20,...,NaN,NaN,NaN,NaN,PGSP11016,Research Skills in the Social Sciences: Data C...,20.0,2024/5,Compulsory,NaN
1,PRMSCMGMNT1F,PRMSCMGMNT1F1,Management (MSc by Research),Business School,HSS,1,CMSE11003,Dissertation (MSc by Research (Management) Mod...,4,60,...,NaN,NaN,NaN,NaN,CMSE11003,Dissertation (MSc by Research (Management) Mod...,60.0,2024/5,Compulsory,NaN
2,PRMSCMGMNT1F,PRMSCMGMNT1F1,Management (MSc by Research),Business School,HSS,1,CMSE11525,Supervised Reading Course,5,20,...,NaN,NaN,NaN,NaN,CMSE11525,Supervised Reading Course,20.0,2024/5,Compulsory,NaN
3,PRMSCMGMNT1F,PRMSCMGMNT1F1,Management (MSc by Research),Business School,HSS,1,PGSP12002,Advanced Research Design and Methods,6,20,...,NaN,NaN,NaN,NaN,PGSP12002,Advanced Research Design and Methods,20.0,2024/5,Compulsory,NaN
4,PRMSCMGMNT1F,PRMSCMGMNT1F1,Management (MSc by Research),Business School,HSS,1,ROU_PRMSCMGMNT1F_4,MSc by Research in Management - Optional Cours...,103,40,...,A,60.0,60.0,AND,BUST11231,Supervised reading: Literature review,20.0,2024/5,Optional,NaN

In [3]:
dpt.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 151405 entries, 0 to 151404
Data columns (total 21 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   Programme Code         151405 non-null  object
 1   ProgYear               151405 non-null  object
 2   Programme Name         151405 non-null  object
 3   Programme School Name  151405 non-null  object
 4   Programme College      151405 non-null  object
 5   Programme Year         151405 non-null  int64
 6   Collection Code        151405 non-null  object
 7   Collection Name        151249 non-null  object
 8   Collection Sequence    151405 non-null  int64
 9   Collection Min Value   151405 non-null  int64
 10  Collection Max Value   151405 non-null  int64
 11  Collection Reg Group   120731 non-null  object
 12  Collection Group Min   120580 non-null  float64
 13  Collection Group Max   120580 non-null  float64
 14  Collection Operand     76051 non-null   object
 15  Course Code            151405 non-null  object
 16  Course Name            151405 non-null  object
 17  SCQF Credits           149834 non-null  float64
 18  Session                151405 non-null  object
 19  Compulsory/Optional    151405 non-null  object
 20  Collection Note        107572 non-null  object
dtypes: float64(3), int64(4), object(14)
memory usage: 24.3+ MB

In [4]:
dpt.describe()

,Programme Year,Collection Sequence,Collection Min Value,Collection Max Value,Collection Group Min,Collection Group Max,SCQF Credits
count,151405.000000,151405.000000,151405.000000,151405.000000,120580.000000,120580.000000,149834.000000
mean,2.196691,111.253354,11.933787,40.917110,61.281307,64.780436,16.493753
std,1.181392,64.729913,18.964874,18.590002,32.023374,29.837399,9.297486
min,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1.000000,102.000000,0.000000,30.000000,40.000000,40.000000,10.000000
50%,2.000000,105.000000,0.000000,40.000000,60.000000,60.000000,20.000000
75%,3.000000,114.000000,20.000000,40.000000,80.000000,80.000000,20.000000
max,7.000000,702.000000,180.000000,180.000000,180.000000,180.000000,180.000000

In [5]:

# -------------------------------------------------------------------
# Define the programme codes for the five programmes of interest
# (as provided in the description)
# -------------------------------------------------------------------
target_codes = [
    "UTMATPH",           # Mathematics & Physics
    "UTBSCMATBU1F",      # Mathematics & Business
    "UTCMPMA",           # Computer Science & Maths
    "UTECNMA",           # Economics & Maths
    "UTPHIMA"            # Philosophy & Maths
]

# -------------------------------------------------------------------
# Filter the dataframe to keep only rows whose Programme Code is in the list
# -------------------------------------------------------------------
years=[3,4]
filtered_dpt = dpt[dpt['Programme Code'].isin(target_codes)]
filtered_dpt=filtered_dpt[filtered_dpt['Programme Year'].isin(years)]
print(filtered_dpt['Compulsory/Optional'].unique())
filtered_dpt.info()

['Optional' 'Compulsory' 'Optional-Open']
<class 'pandas.core.frame.DataFrame'>
Index: 884 entries, 84048 to 149727
Data columns (total 21 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Programme Code         884 non-null    object
 1   ProgYear               884 non-null    object
 2   Programme Name         884 non-null    object
 3   Programme School Name  884 non-null    object
 4   Programme College      884 non-null    object
 5   Programme Year         884 non-null    int64
 6   Collection Code        884 non-null    object
 7   Collection Name        884 non-null    object
 8   Collection Sequence    884 non-null    int64
 9   Collection Min Value   884 non-null    int64
 10  Collection Max Value   884 non-null    int64
 11  Collection Reg Group   839 non-null    object
 12  Collection Group Min   839 non-null    float64
 13  Collection Group Max   839 non-null    float64
 14  Collection Operand     653 non-null    object
 15  Course Code            884 non-null    object
 16  Course Name            884 non-null    object
 17  SCQF Credits           879 non-null    float64
 18  Session                884 non-null    object
 19  Compulsory/Optional    884 non-null    object
 20  Collection Note        310 non-null    object
dtypes: float64(3), int64(4), object(14)
memory usage: 151.9+ KB

In [6]:
pc=pd.read_excel(r'E:\TAOR\Data\Programme-Course.xlsx')
pc.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53962 entries, 0 to 53961
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   CourseId    53962 non-null  object
 1   ModuleId    53962 non-null  object
 2   Compulsory  53962 non-null  bool
dtypes: bool(1), object(2)
memory usage: 896.0+ KB

In [7]:
pc.head()

                  CourseId                   ModuleId  Compulsory
0  PRENGAPLPH2F_YR1_2024/5    XXXX01103_SV1_YR_2024/5       False
1  PRENGAPLPH2F_YR1_2024/5    XXXX01104_SV1_YR_2024/5       False
2  PRENGAPLPH2F_YR1_2024/5    XXXX01101_SV1_YR_2024/5       False
3  PRENGOFFRE1F_YR2_2024/5  PGEE11199_SS1_FLEX_2024/5        True
4  PRENGOFFRE1F_YR2_2024/5  PGEE11192_SS1_FLEX_2024/5        True

In [8]:
filtered_pc = pc[~pc['ModuleId'].str.startswith('MATH', na=False)]
filtered_pc.head()

                  CourseId                   ModuleId  Compulsory
0  PRENGAPLPH2F_YR1_2024/5    XXXX01103_SV1_YR_2024/5       False
1  PRENGAPLPH2F_YR1_2024/5    XXXX01104_SV1_YR_2024/5       False
2  PRENGAPLPH2F_YR1_2024/5    XXXX01101_SV1_YR_2024/5       False
3  PRENGOFFRE1F_YR2_2024/5  PGEE11199_SS1_FLEX_2024/5        True
4  PRENGOFFRE1F_YR2_2024/5  PGEE11192_SS1_FLEX_2024/5        True

In [9]:
filtered_pc = filtered_pc[~filtered_pc['ModuleId'].str.contains('VV', na=False)]
dpt_courses = filtered_dpt[['Course Code']].drop_duplicates()

In [10]:
# Merge DPT with Programme-Course to get ModuleId
dpt_pc = pd.merge(
    filtered_dpt,
    pc,
    left_on="Course Code",
    right_on="CourseId",
    how="left"
)

print(dpt_pc.head())
print(dpt_pc.columns)
print(dpt_pc.info())

  Programme Code  ProgYear                       Programme Name  \
0        UTECNMA  UTECNMA3  Economics and Mathematics (MA Hons)
1        UTECNMA  UTECNMA3  Economics and Mathematics (MA Hons)
2        UTECNMA  UTECNMA3  Economics and Mathematics (MA Hons)
3        UTECNMA  UTECNMA3  Economics and Mathematics (MA Hons)
4        UTECNMA  UTECNMA3  Economics and Mathematics (MA Hons)

  Programme School Name Programme College  Programme Year    Collection Code  \
0   School of Economics               HSS               3  ROU_W_UTECNAC1_10
1   School of Economics               HSS               3  ROU_W_UTECNAC1_10
2   School of Economics               HSS               3  ROU_P_UTMATMU1_10
3   School of Economics               HSS               3  ROU_P_UTMATMU1_10
4   School of Economics               HSS               3  ROU_P_UTMATMU1_10

                                     Collection Name  Collection Sequence  \
0  Economics Course Options for Joint Programmes ...                  210
1  Economics Course Options for Joint Programmes ...                  210
2                         HAlg/HAna/HCoV/HDEq choice                  211
3                         HAlg/HAna/HCoV/HDEq choice                  211
4                         HAlg/HAna/HCoV/HDEq choice                  211

   Collection Min Value  ...  Collection Operand Course Code  \
0                    20  ...                 AND   ECNM10056
1                    20  ...                 AND   ECNM10069
2                    40  ...                 AND   MATH10066
3                    40  ...                 AND   MATH10067
4                    40  ...                 AND   MATH10068

                      Course Name  SCQF Credits Session Compulsory/Optional  \
0    Applications of Econometrics          20.0  2024/5            Optional
1        Topics in Macroeconomics          20.0  2024/5            Optional
2  Honours Differential Equations          20.0  2024/5            Optional
3       Honours Complex Variables          20.0  2024/5            Optional
4                Honours Analysis          20.0  2024/5            Optional

                                     Collection Note  CourseId ModuleId  \
0                                                NaN       NaN      NaN
1                                                NaN       NaN      NaN
2  Students should consult the prerequisites for ...       NaN      NaN
3  Students should consult the prerequisites for ...       NaN      NaN
4  Students should consult the prerequisites for ...       NaN      NaN

  Compulsory
0        NaN
1        NaN
2        NaN
3        NaN
4        NaN

[5 rows x 24 columns]
Index(['Programme Code', 'ProgYear', 'Programme Name', 'Programme School Name',
       'Programme College', 'Programme Year', 'Collection Code',
       'Collection Name', 'Collection Sequence', 'Collection Min Value',
       'Collection Max Value', 'Collection Reg Group', 'Collection Group Min',
       'Collection Group Max', 'Collection Operand', 'Course Code',
       'Course Name', 'SCQF Credits', 'Session', 'Compulsory/Optional',
       'Collection Note', 'CourseId', 'ModuleId', 'Compulsory'],
      dtype='object')
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 884 entries, 0 to 883
Data columns (total 24 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Programme Code         884 non-null    object
 1   ProgYear               884 non-null    object
 2   Programme Name         884 non-null    object
 3   Programme School Name  884 non-null    object
 4   Programme College      884 non-null    object
 5   Programme Year         884 non-null    int64
 6   Collection Code        884 non-null    object
 7   Collection Name        884 non-null    object
 8   Collection Sequence    884 non-null    int64
 9   Collection Min Value   884 non-null    int64
 10  Collection Max Value   884 non-null    int64
 11  Collection Reg Group   839 non-null    object
 12  Collection Group Min   839 non-null    float64
 13  Collection Group Max   839 non-null    float64
 14  Collection Operand     653 non-null    object
 15  Course Code            884 non-null    object
 16  Course Name            884 non-null    object
 17  SCQF Credits           879 non-null    float64
 18  Session                884 non-null    object
 19  Compulsory/Optional    884 non-null    object
 20  Collection Note        310 non-null    object
 21  CourseId               0 non-null      object
 22  ModuleId               0 non-null      object
 23  Compulsory             0 non-null      object
dtypes: float64(3), int64(4), object(17)
memory usage: 165.9+ KB
None

In [11]:
evmr=pd.read_excel(r'E:\TAOR\Data\2024-5 Event Module Room.xlsx')
evmr.head()

,Module Department,Module Code,Module Name,Event ID,Event Name,Event Type,Duration (minutes),Event Size,Timeslot,WholeClass,Online Delivery,Number of Weeks,Weeks,Room,Room type 2,Room Type 1,Building,Campus,Semester,Room Lock
0,Business School,ACCN08007_SS1_SEM1_2024/5,Accountancy 1A,E:96XCWW2M9V,Accountancy 1A - Tutorial/02,Tutorial,50,18.0,Tuesday 11:00,False,NaN,9,"10, 11, 12, 13, 15, 16, 17, 18, 19",0335_01_1.9,General Teaching,Centrally Allocated Space,Lister Learning and Teaching Centre,Central,Semester 1,No
1,Business School,BUST08052_SS1_SEM1_2024/5,Planning for a start-up,E:XT1KZOCGA6,Planning for a start-up - Tutorial/01,Tutorial,110,25.0,Wednesday 10:00,False,NaN,2,"15, 19",0228_-1_LG.10,General Teaching,Centrally Allocated Space,40 George Square Lower Teaching Hub,Central,Semester 1,No
2,Business School,BUST08051_SV1_SEM1_2024/5,Psychological Well-being and Business,E:NB1S2PULQP,Psychological Well-being and Business - Tutori...,Tutorial,110,20.0,Monday 09:00,False,NaN,8,"11, 12, 13, 15, 16, 17, 18, 19",0201_00_G.05,General Teaching,Centrally Allocated Space,Appleton Tower,Central,Semester 1,No
3,Business School,BUST08004_SV1_SEM1_2024/5,Marketing,E:QGLQZOQGIF,Marketing - Tutorial/07,Tutorial,50,14.0,Tuesday 15:00,False,NaN,8,"11, 12, 13, 15, 16, 17, 18, 19",0113_00_G.205,General Teaching,Centrally Allocated Space,"Medical School, Teviot",Central,Semester 1,No
4,Business School,BUST10149_SV1_SEM1_2024/5,"Mergers, Acquisitions, and Corporate Restructu...",E:Y2SNRCC5RT,"Mergers, Acquisitions, and Corporate Restructu...",Lecture,110,120.0,Monday 11:00,True,NaN,2,"9, 17",LectureTheatre_ChambersStreetMuseum,General Teaching,Centrally Allocated Space,Hired Space - Contingency,Central,Semester 1,No

In [12]:
evmr.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32757 entries, 0 to 32756
Data columns (total 20 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Module Department   32757 non-null  object
 1   Module Code         32757 non-null  object
 2   Module Name         32757 non-null  object
 3   Event ID            32757 non-null  object
 4   Event Name          32757 non-null  object
 5   Event Type          32757 non-null  object
 6   Duration (minutes)  32757 non-null  int64
 7   Event Size          32619 non-null  float64
 8   Timeslot            32757 non-null  object
 9   WholeClass          32757 non-null  bool
 10  Online Delivery     989 non-null    object
 11  Number of Weeks     32757 non-null  int64
 12  Weeks               32757 non-null  object
 13  Room                29598 non-null  object
 14  Room type 2         32737 non-null  object
 15  Room Type 1         32602 non-null  object
 16  Building            29598 non-null  object
 17  Campus              29598 non-null  object
 18  Semester            32757 non-null  object
 19  Room Lock           32757 non-null  object
dtypes: bool(1), float64(1), int64(2), object(16)
memory usage: 4.8+ MB

In [13]:
evmr.describe()

       Duration (minutes)    Event Size  Number of Weeks
count        32757.000000  32619.000000     32757.000000
mean           113.452606     44.090193         4.884666
std            108.606265     61.903624         4.117164
min             15.000000      1.000000         1.000000
25%             50.000000     14.000000         1.000000
50%             80.000000     20.000000         3.000000
75%            110.000000     45.000000        10.000000
max           1410.000000    638.000000        22.000000

In [14]:
pc=pd.read_excel(r'E:\TAOR\Data\Programme-Course.xlsx')
pc.head()

                  CourseId                   ModuleId  Compulsory
0  PRENGAPLPH2F_YR1_2024/5    XXXX01103_SV1_YR_2024/5       False
1  PRENGAPLPH2F_YR1_2024/5    XXXX01104_SV1_YR_2024/5       False
2  PRENGAPLPH2F_YR1_2024/5    XXXX01101_SV1_YR_2024/5       False
3  PRENGOFFRE1F_YR2_2024/5  PGEE11199_SS1_FLEX_2024/5        True
4  PRENGOFFRE1F_YR2_2024/5  PGEE11192_SS1_FLEX_2024/5        True

In [15]:
pc.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53962 entries, 0 to 53961
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   CourseId    53962 non-null  object
 1   ModuleId    53962 non-null  object
 2   Compulsory  53962 non-null  bool
dtypes: bool(1), object(2)
memory usage: 896.0+ KB

In [16]:
pc.describe()

                       CourseId                   ModuleId Compulsory
count                     53962                      53962      53962
unique                     3500                       5262          2
top     UTMAHPOPPE1F_YR4_2024/5  LASC08020_SV1_SEM2_2024/5      False
freq                        141                         95      45751

In [17]:
rrt=pd.read_excel(r'E:\TAOR\Data\Rooms and Room Types.xlsx')
rrt.head()

,Id,Description,Capacity,Building,Building.1,Campus,Central/Local,Room Type,Specialist room type,Has a 24-5 Event
0,2701_00_GU108,"Auditorium A, Shirley Hall (GU108) - No Food o...",262,2701,Chancellor's Building,Bioquarter,Locally Allocated Space,Specialist Room,General Teaching,Yes
1,2701_00_GU216,Auditorium B (GU216) - No Food or Drink,150,2701,Chancellor's Building,Bioquarter,Locally Allocated Space,Specialist Room,General Teaching,Yes
2,2701_00_GU302,Micro Lab 1 (GU302),20,2701,Chancellor's Building,Bioquarter,Locally Allocated Space,Specialist Room,Computer Laboratory,Yes
3,2701_00_GU303,Micro Lab 2 (GU303),20,2701,Chancellor's Building,Bioquarter,Locally Allocated Space,Specialist Room,Computer Laboratory,Yes
4,2701_00_GU318,Undergraduate Medical Teaching Room (GU318),96,2701,Chancellor's Building,Bioquarter,Locally Allocated Space,Specialist Room,General Teaching,Yes

In [18]:
rrt.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 649 entries, 0 to 648
Data columns (total 10 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Id                    649 non-null    object
 1   Description           649 non-null    object
 2   Capacity              649 non-null    int64
 3   Building              649 non-null    int64
 4   Building.1            649 non-null    object
 5   Campus                649 non-null    object
 6   Central/Local         649 non-null    object
 7   Room Type             649 non-null    object
 8   Specialist room type  649 non-null    object
 9   Has a 24-5 Event      649 non-null    object
dtypes: int64(2), object(8)
memory usage: 50.8+ KB

In [19]:
rrt.describe()

         Capacity     Building
count  649.000000   649.000000
mean    47.910632   474.308166
std     58.165829   578.364353
min      1.000000     1.000000
25%     16.000000   214.000000
50%     28.000000   421.000000
75%     52.000000   601.000000
max    458.000000  9004.000000

In [20]:
import os
file_path = r'E:\TAOR\Data\2024-5 Student Programme Module Event (5).xlsx'
if os.path.exists(file_path):
    print("File exists")
else:
    print("File not found")

File exists

In [21]:
with pd.ExcelFile(file_path) as xl:
    print(xl.sheet_names)

['2024-5 Student Programme Module']

In [22]:
spm = pd.read_excel(r'E:\TAOR\Data\2024-5 Student Programme Module Event (5).xlsx')

In [23]:
spm.head()

,AnonID,Department,Programme,Programme Code-Year,Course Name,Course ID,Event ID,Semester
0,Student00001,Moray House School of Education and Sport,Leadership and Learning (ICL) (MEd) - 2-6 Year...,PTMEDLEALE1U_YR2_2024/5,Building Capacity and Creating a Culture of Le...,EDUA11432_SS1_YR_2024/5,E:4SAHVIJVD9,Semester 1
1,Student00001,Moray House School of Education and Sport,Leadership and Learning (ICL) (MEd) - 2-6 Year...,PTMEDLEALE1U_YR2_2024/5,Building Capacity and Creating a Culture of Le...,EDUA11432_SS1_YR_2024/5,E:4SAHVIJVD9-00002,Semester 2
2,Student00001,Moray House School of Education and Sport,Leadership and Learning (ICL) (MEd) - 2-6 Year...,PTMEDLEALE1U_YR2_2024/5,Building Capacity and Creating a Culture of Le...,EDUA11432_SS1_YR_2024/5,E:4SAHVIJVD9-00001,Semester 1
3,Student00002,School of Health in Social Science,Counselling Studies (PhD) (Part-time) (Year 1),PRPHDCOUST1P_YR1_2024/5,Autoethnographic Research Methods in the Socia...,CNST11079_SV1_SEM2_2024/5,E:M636SRK7S4,Semester 2
4,Student00002,School of Health in Social Science,Counselling Studies (PhD) (Part-time) (Year 1),PRPHDCOUST1P_YR1_2024/5,Between Counselling and Research 1: Approaches...,CNST12007_SV1_SEM1_2024/5,E:TWUTXLFVGS,Semester 1

In [24]:
spm.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 930173 entries, 0 to 930172
Data columns (total 8 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   AnonID               930173 non-null  object
 1   Department           930173 non-null  object
 2   Programme            930173 non-null  object
 3   Programme Code-Year  930173 non-null  object
 4   Course Name          930173 non-null  object
 5   Course ID            930173 non-null  object
 6   Event ID             930173 non-null  object
 7   Semester             930173 non-null  object
dtypes: object(8)
memory usage: 56.8+ MB

In [25]:
spm.describe()

,AnonID,Department,Programme,Programme Code-Year,Course Name,Course ID,Event ID,Semester
count,930173,930173,930173,930173,930173,930173,930173,930173
unique,25588,28,2087,2091,3935,4110,29105,2
top,Student10113,Royal (Dick) School of Veterinary Studies,Medicine (Pre-Clinical) (MBChB) (Year 1),UTMBCHBMDP1F_YR1_2024/5,Whole body health 1,MBCH08013_SS1_YR_2024/5,E:UYCVOAYZYV,Semester 1
freq,381,200252,58101,58101,57941,57941,914,493133

In [26]:
programmes = [
    'UTMATHB',           # Mathematics
    'UTMATPH',           # Maths & Physics
    'UTBSCMATBU1F',      # Maths & Business
    'UTCMPMA',           # Computer Science & Maths
    'UTECNMA',           # Economics & Maths
    'UTPHIMA'            # Philosophy & Maths
]

# -------------------------------------------------------------------
# 3. Filter spm to only students in these programmes
# -------------------------------------------------------------------
# spm['Programme Code-Year'] contains strings like "PTMEDLEALE1U_YR2_2024/5"
# We extract the base programme code (everything before '_YR')
spm['ProgBase'] = spm['Programme Code-Year'].str.split('_YR').str[0]

spm_filt = spm[spm['ProgBase'].isin(programmes)].copy()
print(f"Filtered spm rows: {len(spm_filt)}")

Filtered spm rows: 18296

In [27]:
# Deduplicate evmr: keep first row for each Event ID
evmr_dedup = evmr.drop_duplicates(subset=['Event ID'], keep='first')

# Merge spm_filt with the deduplicated evmr
merged = spm_filt.merge(evmr_dedup, on='Event ID', how='left')

# Drop rows where the merge failed (should be few if Event IDs match)
merged = merged.dropna(subset=['Module Code'])

print(f"Rows after merge: {len(merged)}")

Rows after merge: 18296

In [28]:
merged.head(10)

,AnonID,Department,Programme,Programme Code-Year,Course Name,Course ID,Event ID,Semester_x,ProgBase,Module Department,...,Online Delivery,Number of Weeks,Weeks,Room,Room type 2,Room Type 1,Building,Campus,Semester_y,Room Lock
0,Student00397,School of Mathematics,Mathematics (BSc Hons) (Year 4),UTMATHB_YR4_2024/5,Commutative Algebra,MATH10017_SV1_SEM1_2024/5,E:P9W3ZLPQEI,Semester 1,UTMATHB,School of Mathematics,...,NaN,11,"9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19",0613_05_5.5327,General Teaching,Centrally Allocated Space,JCMB,Kings Buildings,Semester 1,No
1,Student00397,School of Mathematics,Mathematics (BSc Hons) (Year 4),UTMATHB_YR4_2024/5,Commutative Algebra,MATH10017_SV1_SEM1_2024/5,E:P9W3ZLPQEI-00001,Semester 1,UTMATHB,School of Mathematics,...,NaN,11,"9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19",0613_05_5.5327,General Teaching,Centrally Allocated Space,JCMB,Kings Buildings,Semester 1,No
2,Student00397,School of Mathematics,Mathematics (BSc Hons) (Year 4),UTMATHB_YR4_2024/5,Commutative Algebra,MATH10017_SV1_SEM1_2024/5,E:VH72L3DQVF,Semester 1,UTMATHB,School of Mathematics,...,NaN,5,"10, 12, 14, 16, 18",0654_00_G.09,Teaching Studio,Centrally Allocated Space,Murchison House,Kings Buildings,Semester 1,No (but must go in a room Type: Teaching Studio)
3,Student00397,School of Mathematics,Mathematics (BSc Hons) (Year 4),UTMATHB_YR4_2024/5,Fundamentals of Operational Research,MATH10065_SV1_SEM1_2024/5,E:XRH2KSOXA5,Semester 1,UTMATHB,School of Mathematics,...,NaN,11,"9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19",0640_00_G.0070,General Teaching,Centrally Allocated Space,Ashworth Labs,Kings Buildings,Semester 1,No
4,Student00397,School of Mathematics,Mathematics (BSc Hons) (Year 4),UTMATHB_YR4_2024/5,Fundamentals of Operational Research,MATH10065_SV1_SEM1_2024/5,E:6VTFZ3WAD9-00001,Semester 1,UTMATHB,School of Mathematics,...,NaN,5,"10, 12, 14, 16, 18",0613_04_4.4325C,Teaching Studio,Centrally Allocated Space,JCMB,Kings Buildings,Semester 1,No (but must go in a room Type: Teaching Studio)
5,Student00397,School of Mathematics,Mathematics (BSc Hons) (Year 4),UTMATHB_YR4_2024/5,Fundamentals of Optimization,MATH11111_SS1_SEM1_2024/5,E:YLWG5JYNSR,Semester 1,UTMATHB,School of Mathematics,...,NaN,11,"9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19",0639_-1_B.01,General Teaching,Centrally Allocated Space,Nucleus,Kings Buildings,Semester 1,No
6,Student00397,School of Mathematics,Mathematics (BSc Hons) (Year 4),UTMATHB_YR4_2024/5,Fundamentals of Optimization,MATH11111_SS1_SEM1_2024/5,E:G4GFQBJ6AT-00001,Semester 1,UTMATHB,School of Mathematics,...,NaN,6,"9, 11, 13, 15, 17, 19",0613_01_1.1501,General Teaching,Centrally Allocated Space,JCMB,Kings Buildings,Semester 1,No
7,Student00715,School of Mathematics,Mathematics (BSc Hons) (Year 4),UTMATHB_YR4_2024/5,Applied Statistics,MATH10096_SV1_SEM2_2024/5,E:3COI9CWIA8,Semester 2,UTMATHB,School of Mathematics,...,NaN,11,"26, 27, 28, 29, 30, 32, 33, 34, 35, 36, 37",0613_02_2.3902,General Teaching,Centrally Allocated Space,JCMB,Kings Buildings,Semester 2,No
8,Student00715,School of Mathematics,Mathematics (BSc Hons) (Year 4),UTMATHB_YR4_2024/5,Applied Statistics,MATH10096_SV1_SEM2_2024/5,E:3COI9CWIA8-00001,Semester 2,UTMATHB,School of Mathematics,...,NaN,11,"26, 27, 28, 29, 30, 32, 33, 34, 35, 36, 37",0613_02_2.3902,General Teaching,Centrally Allocated Space,JCMB,Kings Buildings,Semester 2,No
9,Student00715,School of Mathematics,Mathematics (BSc Hons) (Year 4),UTMATHB_YR4_2024/5,Applied Statistics,MATH10096_SV1_SEM2_2024/5,E:K9ZW1XHPT7-00003,Semester 2,UTMATHB,School of Mathematics,...,NaN,5,"27, 29, 32, 34, 36",0613_03_3.3217,Teaching Studio,Centrally Allocated Space,JCMB,Kings Buildings,Semester 2,No (but must go in a room Type: Teaching Studio)

In [29]:
merged['ModCode'] = merged['Course ID'].str.split('_').str[0]

# Extract module code from pc['ModuleId']
pc['ModCode'] = pc['ModuleId'].str.split('_').str[0]

# Extract programme base code from pc['CourseId'] (first part before '_YR')
pc['ProgBase'] = pc['CourseId'].str.split('_YR').str[0]
pc_agg = pc.groupby(['ProgBase', 'ModCode'], as_index=False)['Compulsory'].max()
# Now merge merged (student data) with pc on (ProgBase, ModCode)
merged = merged.merge(pc_agg[['ProgBase', 'ModCode', 'Compulsory']],
                      on=['ProgBase', 'ModCode'], how='left')
merged.head()

,AnonID,Department,Programme,Programme Code-Year,Course Name,Course ID,Event ID,Semester_x,ProgBase,Module Department,...,Weeks,Room,Room type 2,Room Type 1,Building,Campus,Semester_y,Room Lock,ModCode,Compulsory
0,Student00397,School of Mathematics,Mathematics (BSc Hons) (Year 4),UTMATHB_YR4_2024/5,Commutative Algebra,MATH10017_SV1_SEM1_2024/5,E:P9W3ZLPQEI,Semester 1,UTMATHB,School of Mathematics,...,"9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19",0613_05_5.5327,General Teaching,Centrally Allocated Space,JCMB,Kings Buildings,Semester 1,No,MATH10017,False
1,Student00397,School of Mathematics,Mathematics (BSc Hons) (Year 4),UTMATHB_YR4_2024/5,Commutative Algebra,MATH10017_SV1_SEM1_2024/5,E:P9W3ZLPQEI-00001,Semester 1,UTMATHB,School of Mathematics,...,"9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19",0613_05_5.5327,General Teaching,Centrally Allocated Space,JCMB,Kings Buildings,Semester 1,No,MATH10017,False
2,Student00397,School of Mathematics,Mathematics (BSc Hons) (Year 4),UTMATHB_YR4_2024/5,Commutative Algebra,MATH10017_SV1_SEM1_2024/5,E:VH72L3DQVF,Semester 1,UTMATHB,School of Mathematics,...,"10, 12, 14, 16, 18",0654_00_G.09,Teaching Studio,Centrally Allocated Space,Murchison House,Kings Buildings,Semester 1,No (but must go in a room Type: Teaching Studio),MATH10017,False
3,Student00397,School of Mathematics,Mathematics (BSc Hons) (Year 4),UTMATHB_YR4_2024/5,Fundamentals of Operational Research,MATH10065_SV1_SEM1_2024/5,E:XRH2KSOXA5,Semester 1,UTMATHB,School of Mathematics,...,"9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19",0640_00_G.0070,General Teaching,Centrally Allocated Space,Ashworth Labs,Kings Buildings,Semester 1,No,MATH10065,False
4,Student00397,School of Mathematics,Mathematics (BSc Hons) (Year 4),UTMATHB_YR4_2024/5,Fundamentals of Operational Research,MATH10065_SV1_SEM1_2024/5,E:6VTFZ3WAD9-00001,Semester 1,UTMATHB,School of Mathematics,...,"10, 12, 14, 16, 18",0613_04_4.4325C,Teaching Studio,Centrally Allocated Space,JCMB,Kings Buildings,Semester 1,No (but must go in a room Type: Teaching Studio),MATH10065,False

In [30]:
# merged = merged.dropna(subset=['Compulsory'])

print(f"Rows after determining compulsory: {len(merged)}")

Rows after determining compulsory: 18296

In [31]:
evmr_dedup=evmr_dedup[evmr_dedup['WholeClass']]
evmr=evmr_dedup

In [32]:
evmr['Day'] = evmr['Timeslot'].str.split().str[0]   # Monday, Tuesday, ...
evmr['Hour'] = evmr['Timeslot'].str.split().str[1]  # "11:00" etc.

In [33]:
evmr['HourNum'] = pd.to_datetime(evmr['Hour'], format='%H:%M').dt.hour + pd.to_datetime(evmr['Hour'], format='%H:%M').dt.minute/60
module_events = evmr.groupby('Module Code').agg({
    'Day': list,
    'HourNum': list,
    'Campus': list
}).reset_index()
module_events.columns = ['Module Code', 'Days', 'Hours', 'Campuses']

In [34]:

travel_data = [
    ("Bioquarter", "Bioquarter", 0),
    ("Central", "Bioquarter", 60),
    ("Easter Bush", "Bioquarter", 60),
    ("Holyrood", "Bioquarter", 60),
    ("King's Buildings", "Bioquarter", 60),
    ("Lauriston", "Bioquarter", 60),
    ("New College", "Bioquarter", 60),
    ("Western General", "Bioquarter", 60),
    ("Bioquarter", "Central", 60),
    ("Central", "Central", 0),
    ("Easter Bush", "Central", 60),
    ("Holyrood", "Central", 10),
    ("King's Buildings", "Central", 30),
    ("Lauriston", "Central", 10),
    ("New College", "Central", 10),
    ("Western General", "Central", 60),
    ("Bioquarter", "Easter Bush", 60),
    ("Central", "Easter Bush", 60),
    ("Easter Bush", "Easter Bush", 0),
    ("Holyrood", "Easter Bush", 60),
    ("King's Buildings", "Easter Bush", 60),
    ("Lauriston", "Easter Bush", 60),
    ("New College", "Easter Bush", 60),
    ("Western General", "Easter Bush", 60),
    ("Bioquarter", "Holyrood", 60),
    ("Central", "Holyrood", 10),
    ("Easter Bush", "Holyrood", 60),
    ("Holyrood", "Holyrood", 0),
    ("King's Buildings", "Holyrood", 30),
    ("Lauriston", "Holyrood", 10),
    ("New College", "Holyrood", 10),
    ("Western General", "Holyrood", 60),
    ("Bioquarter", "King's Buildings", 60),
    ("Central", "King's Buildings", 30),
    ("Easter Bush", "King's Buildings", 60),
    ("Holyrood", "King's Buildings", 30),
    ("King's Buildings", "King's Buildings", 0),
    ("Lauriston", "King's Buildings", 30),
    ("New College", "King's Buildings", 30),
    ("Western General", "King's Buildings", 60),
    ("Bioquarter", "Lauriston", 60),
    ("Central", "Lauriston", 10),
    ("Easter Bush", "Lauriston", 60),
    ("Holyrood", "Lauriston", 10),
    ("King's Buildings", "Lauriston", 30),
    ("Lauriston", "Lauriston", 0),
    ("New College", "Lauriston", 10),
    ("Western General", "Lauriston", 60),
    ("Bioquarter", "New College", 60),
    ("Central", "New College", 10),
    ("Easter Bush", "New College", 60),
    ("Holyrood", "New College", 10),
    ("King's Buildings", "New College", 30),
    ("Lauriston", "New College", 10),
    ("New College", "New College", 0),
    ("Western General", "New College", 60),
    ("Bioquarter", "Western General", 60),
    ("Central", "Western General", 60),
    ("Easter Bush", "Western General", 60),
    ("Holyrood", "Western General", 60),
    ("King's Buildings", "Western General", 60),
    ("Lauriston", "Western General", 60),
    ("New College", "Western General", 60),
    ("Western General", "Western General", 0)
]

# Create a dictionary for fast lookup
travel_time_dict = {}
for from_camp, to_camp, tt in travel_data:
    travel_time_dict[(from_camp, to_camp)] = tt

In [35]:
# -------------------------------------------------------------------
# Parse Day and Hour from Timeslot, compute DayNum and ModelHour
# -------------------------------------------------------------------
merged['Day'] = merged['Timeslot'].str.split().str[0]
merged['Hour'] = merged['Timeslot'].str.split().str[1]
merged['HourNum'] = pd.to_datetime(merged['Hour'], format='%H:%M').dt.hour + pd.to_datetime(merged['Hour'], format='%H:%M').dt.minute/60

# Keep only lectures and drop rows without Compulsory
merged = merged[merged['WholeClass'] == True].copy()
merged = merged.dropna(subset=['Compulsory']).copy()

# Map day names to indices (0=Monday,...,4=Friday)
day_order = {'Monday':0, 'Tuesday':1, 'Wednesday':2, 'Thursday':3, 'Friday':4, 'Saturday':5, 'Sunday':6}
merged['DayNum'] = merged['Day'].map(day_order)

# Model hour: 0 = 9am, 8 = 5pm
merged['ModelHour'] = (merged['HourNum'] - 9).round().astype(int)
# Split by semester
sem1 = merged[merged['Semester_y'] == 'Semester 1'].copy()
sem2 = merged[merged['Semester_y'] == 'Semester 2'].copy()
print(f"Semester 1 rows: {len(sem1)}")
print(f"Semester 2 rows: {len(sem2)}")

Semester 1 rows: 5481
Semester 2 rows: 4613

In [36]:
print(pc_agg.head())

       ProgBase    ModCode  Compulsory
0  PRENGAPLPH2F  XXXX01101       False
1  PRENGAPLPH2F  XXXX01103       False
2  PRENGAPLPH2F  XXXX01104       False
3  PRENGOFFRE1F  PGEE11095        True
4  PRENGOFFRE1F  PGEE11190        True

In [37]:
print(pc_agg.info())
print(pc_agg.describe())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39721 entries, 0 to 39720
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ProgBase    39721 non-null  object
 1   ModCode     39721 non-null  object
 2   Compulsory  39721 non-null  bool
dtypes: bool(1), object(2)
memory usage: 659.6+ KB
None
            ProgBase    ModCode Compulsory
count          39721      39721      39721
unique          1480       5205          2
top     UTMAHPOPPE1F  LASC08020      False
freq             172         95      31648

In [38]:
def compute_metrics_with_travel(events):
    """
    events : list of tuples (day_num, hour, campus, duration_minutes)
    Returns dict with keys:
        late (events at hour == 8),
        lunch (events at hour in {3,4}),
        isolated (hour 1..7 with event and no event at h±1, same day),
        days (number of distinct days with any event),
        wednesday (events on Wednesday (day 2) with hour >= 4),
        travel (total travel minutes between consecutive events on same day)
    """
    if not events:
        return {'late':0, 'lunch':0, 'isolated':0, 'days':0, 'wednesday':0, 'travel':0}
    
    # Sort by day then hour
    events.sort(key=lambda x: (x[0], x[1]))
    
    event_set = {(d, h) for d, h, _, _ in events}
    late = 0
    lunch = 0
    wednesday = 0
    days_set = set()
    travel = 0
    
    # First pass: count simple metrics and collect days
    for d, h, _, _ in events:
        days_set.add(d)
        if h == 8:
            late += 1
        if h in (3,4):
            lunch += 1
        if d == 2 and h >= 4:
            wednesday += 1
    
    # Isolated hours: h=1..7, event present, no event at h-1 or h+1 on same day
    isolated = 0
    for d, h, _, _ in events:
        if 1 <= h <= 7:
            if (d, h-1) not in event_set and (d, h+1) not in event_set:
                isolated += 1
    
    # Travel between consecutive events on the same day
    for i in range(len(events)-1):
        d1, h1, camp1, dur1 = events[i]
        d2, h2, camp2, dur2 = events[i+1]
        if d1 == d2:
            # travel time between campuses
            key = (camp1, camp2)
            travel += travel_time_dict.get(key, 60)   # default 60 min if unknown
            # Gap not used – we skip it as requested
    return {
        'late': late,
        'lunch': lunch,
        'isolated': isolated,
        'days': len(days_set),
        'wednesday': wednesday,
        'travel': travel
    }

In [39]:
# Apply Monday-Friday filter (days 0-4) to sem1
sem1 = sem1[sem1['DayNum'].isin([0,1,2,3,4])].copy()
# -------------------------------------------------------------------
# Build module_event_map (one entry per base module)
# -------------------------------------------------------------------
module_events = {}
for _, row in sem1.iterrows():
    base = row['ModCode']
    event = (row['DayNum'], row['ModelHour'], row['Campus'], row['Duration (minutes)'])
    module_events.setdefault(base, []).append(event)
# Deduplicate events per module
for base in module_events:
    module_events[base] = list(set(module_events[base]))

# -------------------------------------------------------------------
# Helper: check if candidate events clash with baseline events
# -------------------------------------------------------------------
def has_clash(baseline_events, cand_events):
    baseline_set = {(d, h) for d, h, _, _ in baseline_events}
    for d, h, _, _ in cand_events:
        if (d, h) in baseline_set:
            return True
    return False

# -------------------------------------------------------------------
# Build estimation dataset using bundle replacement
# -------------------------------------------------------------------
estimation_rows = []

for student_id in sem1['AnonID'].unique():
    student_df = sem1[sem1['AnonID'] == student_id]
    prog_base = student_df['ProgBase'].iloc[0]
    
    # Compulsory modules (unique)
    comp_bases = set(student_df[student_df['Compulsory'] == True]['ModCode'])
    comp_events = []
    for base in comp_bases:
        comp_events.extend(module_events.get(base, []))
    
    # Chosen optional modules (unique)
    chosen_bases = set(student_df[student_df['Compulsory'] == False]['ModCode']) & set(module_events.keys())    
    if not chosen_bases:
        continue
    
    # Universal optional modules for this programme: those marked optional in pc_agg,
    # plus the chosen modules (since they are obviously available).
    optional_for_prog = set(pc_agg[(pc_agg['ProgBase'] == prog_base) & (pc_agg['Compulsory'] == False)]['ModCode'])
    optional_universe = optional_for_prog & set(module_events.keys())
    optional_universe.update(chosen_bases)   # ensure chosen modules are included
    # Diagnostic
    print(f"Student {student_id}: comp_bases {comp_bases}")
    print(f"chosen_bases {chosen_bases}")
    print(f"optional_for_prog size {len(optional_for_prog)}")
    print(f"sem1_base_modules size {len(set(module_events.keys()))}")
    print(f"optional_universe size {len(optional_universe)}")
    if len(optional_universe) == 0:
        print("optional_universe is empty – check pc_agg and module_events keys")
        continue   # skip this student
    print("Number of module_events keys:", len(module_events))
    
    sample_student = sem1['AnonID'].iloc[0]
    sd = sem1[sem1['AnonID'] == sample_student]
    
    print("Sample student:", sample_student)
    print("Chosen ModCodes:", set(sd[sd['Compulsory'] == False]['ModCode']))
    
    for base in set(sd[sd['Compulsory'] == False]['ModCode']):
        print(base, "events:", len(module_events.get(base, [])))
    for chosen_base in chosen_bases:
        # Baseline schedule: compulsory + all other chosen optionals (exclude chosen_base)
        other_optional_bases = chosen_bases - {chosen_base}
        baseline_events = comp_events.copy()
        for base in other_optional_bases:
            baseline_events.extend(module_events.get(base, []))
        baseline = compute_metrics_with_travel(baseline_events)
        
        # Candidate modules: from optional_universe that are not already in chosen_bases
        # (the chosen_base itself is the "chosen" alternative)
        candidate_bases = list(optional_universe - chosen_bases)
        # if len(candidate_bases) > K:
        #     candidate_bases = np.random.choice(candidate_bases, size=K, replace=False).tolist()
        # else:
        #     candidate_bases = list(candidate_bases)
        
        all_candidates = candidate_bases + [chosen_base]
        # The chosen module is one of the candidates (we'll add it separately)
        
        for cand_base in all_candidates:
            cand_events = module_events.get(cand_base, [])
            if not cand_events:
                continue
            # Skip if candidate (other than the chosen one) clashes with baseline schedule
            if cand_base != chosen_base and has_clash(baseline_events, cand_events):
                continue
            combined_events = baseline_events + cand_events
            combined = compute_metrics_with_travel(combined_events)
            
            inc_late = combined['late'] - baseline['late']
            inc_lunch = combined['lunch'] - baseline['lunch']
            inc_isolated = combined['isolated'] - baseline['isolated']
            inc_days = combined['days'] - baseline['days']
            inc_wednesday = combined['wednesday'] - baseline['wednesday']
            inc_travel = combined['travel'] - baseline['travel']
            
            # Scale travel to keep magnitude reasonable
            # inc_travel /= 10
            
            chosen_flag = 1 if cand_base == chosen_base else 0
            if cand_base == chosen_base:
                print(f"Adding row for student {student_id}, chosen module {cand_base}")
            estimation_rows.append({
                'student_id': student_id,
                'module': cand_base,
                'chosen': chosen_flag,
                'inc_late': inc_late,
                'inc_lunch': inc_lunch,
                'inc_isolated': inc_isolated,
                'inc_days': inc_days,
                'inc_wednesday': inc_wednesday,
                'inc_travel': inc_travel
            })

choice_data = pd.DataFrame(estimation_rows)
print(f"Choice dataset shape: {choice_data.shape}")
print(choice_data.head())

Student Student00397: comp_bases set()
chosen_bases {'MATH10017', 'MATH10065', 'MATH11111'}
optional_for_prog size 74
sem1_base_modules size 116
optional_universe size 30
Number of module_events keys: 116
Sample student: Student00397
Chosen ModCodes: {'MATH10017', 'MATH11111', 'MATH10065'}
MATH10017 events: 2
MATH11111 events: 1
MATH10065 events: 1
Adding row for student Student00397, chosen module MATH10017
Adding row for student Student00397, chosen module MATH10065
Adding row for student Student00397, chosen module MATH11111
Student Student00715: comp_bases set()
chosen_bases {'MATH10007', 'MATH10024', 'MATH11088', 'MATH10065', 'MATH11111'}
optional_for_prog size 74
sem1_base_modules size 116
optional_universe size 30
Number of module_events keys: 116
Sample student: Student00397
Chosen ModCodes: {'MATH10017', 'MATH11111', 'MATH10065'}
MATH10017 events: 2
MATH11111 events: 1
MATH10065 events: 1
Adding row for student Student00715, chosen module MATH10007
Adding row for student Student00715, chosen module MATH10024
Adding row for student Student00715, chosen module MATH11088
Adding row for student Student00715, chosen module MATH10065
Adding row for student Student00715, chosen module MATH11111
Student Student00866: comp_bases {'MATH10066'}
chosen_bases {'BUST10160'}
optional_for_prog size 129
sem1_base_modules size 116
optional_universe size 41
Number of module_events keys: 116
Sample student: Student00397
Chosen ModCodes: {'MATH10017', 'MATH11111', 'MATH10065'}
MATH10017 events: 2
MATH11111 events: 1
MATH10065 events: 1
Adding row for student Student00866, chosen module BUST10160
Student Student01181: comp_bases set()
chosen_bases {'INFR10080', 'INFR10061'}
optional_for_prog size 61
sem1_base_modules size 116
optional_universe size 28
Number of module_events keys: 116
Sample student: Student00397
Chosen ModCodes: {'MATH10017', 'MATH11111', 'MATH10065'}
MATH10017 events: 2
MATH11111 events: 1
MATH10065 events: 1
Adding row for student Student01181, chosen module INFR10080
Adding row for student Student01181, chosen module INFR10061
Student Student01289: comp_bases set()
chosen_bases {'INFR10052', 'INFR10080', 'INFR10061'}
optional_for_prog size 61
sem1_base_modules size 116
optional_universe size 28
Number of module_events keys: 116
Sample student: Student00397
Chosen ModCodes: {'MATH10017', 'MATH11111', 'MATH10065'}
MATH10017 events: 2
MATH11111 events: 1
MATH10065 events: 1
Adding row for student Student01289, chosen module INFR10052
Adding row for student Student01289, chosen module INFR10080
Adding row for student Student01289, chosen module INFR10061
Student Student01651: comp_bases set()
chosen_bases {'BUST10158'}
optional_for_prog size 129
sem1_base_modules size 116
optional_universe size 41
Number of module_events keys: 116
Sample student: Student00397
Chosen ModCodes: {'MATH10017', 'MATH11111', 'MATH10065'}
MATH10017 events: 2
MATH11111 events: 1
MATH10065 events: 1
Adding row for student Student01651, chosen module BUST10158
Student Student01733: comp_bases set()
chosen_bases {'MATH10017', 'MATH10013', 'MATH10095'}
optional_for_prog size 74
sem1_base_modules size 116
optional_universe size 30
Number of module_events keys: 116
Sample student: Student00397
Chosen ModCodes: {'MATH10017', 'MATH11111', 'MATH10065'}
MATH10017 events: 2
MATH11111 events: 1
MATH10065 events: 1
Adding row for student Student01733, chosen module MATH10017
Adding row for student Student01733, chosen module MATH10013
Adding row for student Student01733, chosen module MATH10095
Student Student02070: comp_bases set()
chosen_bases {'INFR11114', 'LASC10061', 'INFR10087'}
optional_for_prog size 61
sem1_base_modules size 116
optional_universe size 28
Number of module_events keys: 116
Sample student: Student00397
Chosen ModCodes: {'MATH10017', 'MATH11111', 'MATH10065'}
MATH10017 events: 2
MATH11111 events: 1
MATH10065 events: 1
Adding row for student Student02070, chosen module INFR11114
Adding row for student Student02070, chosen module LASC10061
Adding row for student Student02070, chosen module INFR10087
Student Student02139: comp_bases set()
chosen_bases {'MATH10017', 'MATH10079', 'MATH10065', 'MATH10076'}
optional_for_prog size 74
sem1_base_modules size 116
optional_universe size 30
Number of module_events keys: 116
Sample student: Student00397
Chosen ModCodes: {'MATH10017', 'MATH11111', 'MATH10065'}
MATH10017 events: 2
MATH11111 events: 1
MATH10065 events: 1
Adding row for student Student02139, chosen module MATH10017
Adding row for student Student02139, chosen module MATH10079
Adding row for student Student02139, chosen module MATH10065
Adding row for student Student02139, chosen module MATH10076
Student Student02249: comp_bases set()
chosen_bases {'MATH10098', 'MATH10074', 'MATH10047', 'MATH10065', 'MATH10072'}
optional_for_prog size 74
sem1_base_modules size 116
optional_universe size 30
Number of module_events keys: 116
Sample student: Student00397
Chosen ModCodes: {'MATH10017', 'MATH11111', 'MATH10065'}
MATH10017 events: 2
MATH11111 events: 1
MATH10065 events: 1
Adding row for student Student02249, chosen module MATH10098
Adding row for student Student02249, chosen module MATH10074
Adding row for student Student02249, chosen module MATH10047
Adding row for student Student02249, chosen module MATH10065
Adding row for student Student02249, chosen module MATH10072
Student Student02337: comp_bases {'MATH10066', 'MATH10068'}
chosen_bases {'MATH10074', 'MATH10007', 'MATH08068'}
optional_for_prog size 74
sem1_base_modules size 116
optional_universe size 30
Number of module_events keys: 116
Sample student: Student00397
Chosen ModCodes: {'MATH10017', 'MATH11111', 'MATH10065'}
MATH10017 events: 2
MATH11111 events: 1
MATH10065 events: 1
Adding row for student Student02337, chosen module MATH10074
Adding row for student Student02337, chosen module MATH10007
Adding row for student Student02337, chosen module MATH08068
Student Student02350: comp_bases set()
chosen_bases {'MATH10024', 'MATH10053', 'MATH10065', 'MATH10072', 'MATH10028'}
optional_for_prog size 74
sem1_base_modules size 116
optional_universe size 30
Number of module_events keys: 116
Sample student: Student00397
Chosen ModCodes: {'MATH10017', 'MATH11111', 'MATH10065'}
MATH10017 events: 2
MATH11111 events: 1
MATH10065 events: 1
Adding row for student Student02350, chosen module MATH10024
Adding row for student Student02350, chosen module MATH10053
Adding row for student Student02350, chosen module MATH10065
Adding row for student Student02350, chosen module MATH10072
Adding row for student Student02350, chosen module MATH10028
Student Student02367: comp_bases set()
chosen_bases {'MATH10095', 'MATH10100', 'MATH10098', 'MATH10074', 'MATH10013'}
optional_for_prog size 74
sem1_base_modules size 116
optional_universe size 30
Number of module_events keys: 116
Sample student: Student00397
Chosen ModCodes: {'MATH10017', 'MATH11111', 'MATH10065'}
MATH10017 events: 2
MATH11111 events: 1
MATH10065 events: 1
Adding row for student Student02367, chosen module MATH10095
Adding row for student Student02367, chosen module MATH10100
Adding row for student Student02367, chosen module MATH10098
Adding row for student Student02367, chosen module MATH10074
Adding row for student Student02367, chosen module MATH10013
Student Student02412: comp_bases {'MATH08066', 'MATH08063'}
chosen_bases {'MATH08068'}
optional_for_prog size 74
sem1_base_modules size 116
optional_universe size 30
Number of module_events keys: 116
Sample student: Student00397
Chosen ModCodes: {'MATH10017', 'MATH11111', 'MATH10065'}
MATH10017 events: 2
MATH11111 events: 1
MATH10065 events: 1
Adding row for student Student02412, chosen module MATH08068
Student Student02484: comp_bases set()
chosen_bases {'MATH10053', 'MATH10013', 'MATH10100', 'MATH10065'}
optional_for_prog size 74
sem1_base_modules size 116
optional_universe size 30
Number of module_events keys: 116
Sample student: Student00397
Chosen ModCodes: {'MATH10017', 'MATH11111', 'MATH10065'}
MATH10017 events: 2
MATH11111 events: 1
MATH10065 events: 1
Adding row for student Student02484, chosen module MATH10053
Adding row for student Student02484, chosen module MATH10013
Adding row for student Student02484, chosen module MATH10100
Adding row for student Student02484, chosen module MATH10065
Student Student02503: comp_bases set()
chosen_bases {'BUST10133', 'MATH10053', 'MATH10100', 'MATH10065'}
optional_for_prog size 129
sem1_base_modules size 116
optional_universe size 41
Number of module_events keys: 116
Sample student: Student00397
Chosen ModCodes: {'MATH10017', 'MATH11111', 'MATH10065'}
MATH10017 events: 2
MATH11111 events: 1
MATH10065 events: 1
Adding row for student Student02503, chosen module BUST10133
Adding row for student Student02503, chosen module MATH10053
Adding row for student Student02503, chosen module MATH10100
Adding row for student Student02503, chosen module MATH10065
Student Student02574: comp_bases set()
chosen_bases {'MATH10053', 'MATH10013', 'BUST10151', 'MATH10065'}
optional_for_prog size 129
sem1_base_modules size 116
optional_universe size 41
Number of module_events keys: 116
Sample student: Student00397
Chosen ModCodes: {'MATH10017', 'MATH11111', 'MATH10065'}
MATH10017 events: 2
MATH11111 events: 1
MATH10065 events: 1
Adding row for student Student02574, chosen module MATH10053
Adding row for student Student02574, chosen module MATH10013
Adding row for student Student02574, chosen module BUST10151
Adding row for student Student02574, chosen module MATH10065
Student Student02576: comp_bases set()
chosen_bases {'MATH10065', 'MATH11111'}
optional_for_prog size 74
sem1_base_modules size 116
optional_universe size 30
Number of module_events keys: 116
Sample student: Student00397
Chosen ModCodes: {'MATH10017', 'MATH11111', 'MATH10065'}
MATH10017 events: 2
MATH11111 events: 1
MATH10065 events: 1
Adding row for student Student02576, chosen module MATH10065
Adding row for student Student02576, chosen module MATH11111
Student Student02631: comp_bases set()
chosen_bases {'MATH10007', 'MATH10098', 'MATH11177', 'MATH10072', 'MATH10028'}
optional_for_prog size 74
sem1_base_modules size 116
optional_universe size 30
Number of module_events keys: 116
Sample student: Student00397
Chosen ModCodes: {'MATH10017', 'MATH11111', 'MATH10065'}
MATH10017 events: 2
MATH11111 events: 1
MATH10065 events: 1
Adding row for student Student02631, chosen module MATH10007
Adding row for student Student02631, chosen module MATH10098
Adding row for student Student02631, chosen module MATH11177
Adding row for student Student02631, chosen module MATH10072
Adding row for student Student02631, chosen module MATH10028
Student Student02693: comp_bases {'MATH10066', 'MATH10068'}
chosen_bases {'MATH10072', 'MATH10095'}
optional_for_prog size 74
sem1_base_modules size 116
optional_universe size 30
Number of module_events keys: 116
Sample student: Student00397
Chosen ModCodes: {'MATH10017', 'MATH11111', 'MATH10065'}
MATH10017 events: 2
MATH11111 events: 1
MATH10065 events: 1
Adding row for student Student02693, chosen module MATH10072
Adding row for student Student02693, chosen module MATH10095
Student Student02884: comp_bases set()
chosen_bases {'ECNM10116', 'MATH10095', 'MATH11088'}
optional_for_prog size 101
sem1_base_modules size 116
optional_universe size 37
Number of module_events keys: 116
Sample student: Student00397
Chosen ModCodes: {'MATH10017', 'MATH11111', 'MATH10065'}
MATH10017 events: 2
MATH11111 events: 1
MATH10065 events: 1
Adding row for student Student02884, chosen module ECNM10116
Adding row for student Student02884, chosen module MATH10095
Adding row for student Student02884, chosen module MATH11088
Student Student02944: comp_bases set()
chosen_bases {'MATH10107', 'MATH10007', 'MATH10095', 'MATH10024', 'MATH11111'}
optional_for_prog size 74
sem1_base_modules size 116
optional_universe size 30
Number of module_events keys: 116
Sample student: Student00397
Chosen ModCodes: {'MATH10017', 'MATH11111', 'MATH10065'}
MATH10017 events: 2
MATH11111 events: 1
MATH10065 events: 1
Adding row for student Student02944, chosen module MATH10107
Adding row for student Student02944, chosen module MATH10007
Adding row for student Student02944, chosen module MATH10095
Adding row for student Student02944, chosen module MATH10024
Adding row for student Student02944, chosen module MATH11111
Student Student02951: comp_bases set()
chosen_bases {'MATH10010', 'MATH10099', 'MATH10065'}
optional_for_prog size 74
sem1_base_modules size 116
optional_universe size 30
Number of module_events keys: 116
Sample student: Student00397
Chosen ModCodes: {'MATH10017', 'MATH11111', 'MATH10065'}
MATH10017 events: 2
MATH11111 events: 1
MATH10065 events: 1
Adding row for student Student02951, chosen module MATH10010
Adding row for student Student02951, chosen module MATH10099
Adding row for student Student02951, chosen module MATH10065
Student Student02984: comp_bases set()
chosen_bases {'BUST10133', 'BUST10158', 'MATH10065'}
optional_for_prog size 129
sem1_base_modules size 116
optional_universe size 41
Number of module_events keys: 116
Sample student: Student00397
Chosen ModCodes: {'MATH10017', 'MATH11111', 'MATH10065'}
MATH10017 events: 2
MATH11111 events: 1
MATH10065 events: 1
Adding row for student Student02984, chosen module BUST10133
Adding row for student Student02984, chosen module BUST10158
Adding row for student Student02984, chosen module MATH10065
Student Student03126: comp_bases set()
chosen_bases {'INFR11209', 'INFR11256'}
optional_for_prog size 61
sem1_base_modules size 116
optional_universe size 28
Number of module_events keys: 116
Sample student: Student00397
Chosen ModCodes: {'MATH10017', 'MATH11111', 'MATH10065'}
MATH10017 events: 2
MATH11111 events: 1
MATH10065 events: 1
Adding row for student Student03126, chosen module INFR11209
Adding row for student Student03126, chosen module INFR11256
Student Student03151: comp_bases set()
chosen_bases {'BUST10135', 'MATH10095', 'MATH10098', 'MATH10065'}
optional_for_prog size 129
sem1_base_modules size 116
optional_universe size 41
Number of module_events keys: 116
Sample student: Student00397
Chosen ModCodes: {'MATH10017', 'MATH11111', 'MATH10065'}
MATH10017 events: 2
MATH11111 events: 1
MATH10065 events: 1
Adding row for student Student03151, chosen module BUST10135
Adding row for student Student03151, chosen module MATH10095
Adding row for student Student03151, chosen module MATH10098
Adding row for student Student03151, chosen module MATH10065
Student Student03368: comp_bases set()
chosen_bases {'MATH10017', 'MATH10079', 'MATH11235'}
optional_for_prog size 84
sem1_base_modules size 116
optional_universe size 33
Number of module_events keys: 116
Sample student: Student00397
Chosen ModCodes: {'MATH10017', 'MATH11111', 'MATH10065'}
MATH10017 events: 2
MATH11111 events: 1
MATH10065 events: 1
Adding row for student Student03368, chosen module MATH10017
Adding row for student Student03368, chosen module MATH10079
Adding row for student Student03368, chosen module MATH11235
Student Student03422: comp_bases set()
chosen_bases {'MATH10095', 'ECNM10087', 'MATH11088'}
optional_for_prog size 101
sem1_base_modules size 116
optional_universe size 37
Number of module_events keys: 116
Sample student: Student00397
Chosen ModCodes: {'MATH10017', 'MATH11111', 'MATH10065'}
MATH10017 events: 2
MATH11111 events: 1
MATH10065 events: 1
Adding row for student Student03422, chosen module MATH10095
Adding row for student Student03422, chosen module ECNM10087
Adding row for student Student03422, chosen module MATH11088
Student Student03489: comp_bases set()
chosen_bases {'BUST10124', 'MATH10007', 'BUST10158', 'MATH11088'}
optional_for_prog size 129
sem1_base_modules size 116
optional_universe size 41
Number of module_events keys: 116
Sample student: Student00397
Chosen ModCodes: {'MATH10017', 'MATH11111', 'MATH10065'}
MATH10017 events: 2
MATH11111 events: 1
MATH10065 events: 1
Adding row for student Student03489, chosen module BUST10124
Adding row for student Student03489, chosen module MATH10007
Adding row for student Student03489, chosen module BUST10158
Adding row for student Student03489, chosen module MATH11088
Student Student03721: comp_bases set()
chosen_bases {'MATH11088', 'ECNM10090', 'MATH10065'}
optional_for_prog size 101
sem1_base_modules size 116
optional_universe size 37
Number of module_events keys: 116
Sample student: Student00397
Chosen ModCodes: {'MATH10017', 'MATH11111', 'MATH10065'}
MATH10017 events: 2
MATH11111 events: 1
MATH10065 events: 1
Adding row for student Student03721, chosen module MATH11088
Adding row for student Student03721, chosen module ECNM10090
Adding row for student Student03721, chosen module MATH10065
Student Student03763: comp_bases set()
chosen_bases {'INFR11022', 'INFR11130'}
optional_for_prog size 61
sem1_base_modules size 116
optional_universe size 28
Number of module_events keys: 116
Sample student: Student00397
Chosen ModCodes: {'MATH10017', 'MATH11111', 'MATH10065'}
MATH10017 events: 2
MATH11111 events: 1
MATH10065 events: 1
Adding row for student Student03763, chosen module INFR11022
Adding row for student Student03763, chosen module INFR11130
Student Student03802: comp_bases set()
chosen_bases {'BUST10153', 'MATH10053', 'MATH10013', 'MATH10065'}
optional_for_prog size 129
sem1_base_modules size 116
optional_universe size 41
Number of module_events keys: 116
Sample student: Student00397
Chosen ModCodes: {'MATH10017', 'MATH11111', 'MATH10065'}
MATH10017 events: 2
MATH11111 events: 1
MATH10065 events: 1
Adding row for student Student03802, chosen module BUST10153
Adding row for student Student03802, chosen module MATH10053
Adding row for student Student03802, chosen module MATH10013
Adding row for student Student03802, chosen module MATH10065
Student Student03882: comp_bases set()
chosen_bases {'MATH11088', 'MATH10028', 'MATH10100', 'MATH10065'}
optional_for_prog size 74
sem1_base_modules size 116
optional_universe size 30
Number of module_events keys: 116
Sample student: Student00397
Chosen ModCodes: {'MATH10017', 'MATH11111', 'MATH10065'}
MATH10017 events: 2
MATH11111 events: 1
MATH10065 events: 1
Adding row for student Student03882, chosen module MATH11088
Adding row for student Student03882, chosen module MATH10028
Adding row for student Student03882, chosen module MATH10100
Adding row for student Student03882, chosen module MATH10065
Student Student03934: comp_bases set()
chosen_bases {'MATH10095', 'MATH10099', 'MATH10010', 'MATH10065', 'MATH10013'}
optional_for_prog size 74
sem1_base_modules size 116
optional_universe size 30
Number of module_events keys: 116
Sample student: Student00397
Chosen ModCodes: {'MATH10017', 'MATH11111', 'MATH10065'}
MATH10017 events: 2
MATH11111 events: 1
MATH10065 events: 1
Adding row for student Student03934, chosen module MATH10095
Adding row for student Student03934, chosen module MATH10099
Adding row for student Student03934, chosen module MATH10010
Adding row for student Student03934, chosen module MATH10065
Adding row for student Student03934, chosen module MATH10013
Student Student03998: comp_bases set()
chosen_bases {'MATH10007', 'MATH10013', 'MATH10053', 'MATH10065'}
optional_for_prog size 74
sem1_base_modules size 116
optional_universe size 30
Number of module_events keys: 116
Sample student: Student00397
Chosen ModCodes: {'MATH10017', 'MATH11111', 'MATH10065'}
MATH10017 events: 2
MATH11111 events: 1
MATH10065 events: 1
Adding row for student Student03998, chosen module MATH10007
Adding row for student Student03998, chosen module MATH10013
Adding row for student Student03998, chosen module MATH10053
Adding row for student Student03998, chosen module MATH10065
Student Student04017: comp_bases set()
chosen_bases {'ECNM10116', 'MATH10095', 'MATH10065'}
optional_for_prog size 101
sem1_base_modules size 116
optional_universe size 37
Number of module_events keys: 116
Sample student: Student00397
Chosen ModCodes: {'MATH10017', 'MATH11111', 'MATH10065'}
MATH10017 events: 2
MATH11111 events: 1

In [40]:
# -------------------------------------------------------------------
# Logistic regression to estimate weights (including travel)
# -------------------------------------------------------------------
import statsmodels.api as sm

X = choice_data[['inc_late', 'inc_lunch', 'inc_isolated', 'inc_days', 'inc_wednesday', 'inc_travel']]
X = sm.add_constant(X)
y = choice_data['chosen']

logit_model = sm.Logit(y, X)
result = logit_model.fit()
print(result.summary())
coeffs = result.params
print("\nEstimated coefficients (utility weights):")
print(coeffs)

Optimization terminated successfully.
         Current function value: 0.172962
         Iterations 8
                           Logit Regression Results
==============================================================================
Dep. Variable:                 chosen   No. Observations:                24963
Model:                          Logit   Df Residuals:                    24956
Method:                           MLE   Df Model:                            6
Date:                Fri, 03 Apr 2026   Pseudo R-squ.:                0.008491
Time:                        15:51:46   Log-Likelihood:                -4317.7
converged:                       True   LL-Null:                       -4354.6
Covariance Type:            nonrobust   LLR p-value:                 6.299e-14
=================================================================================
                    coef    std err          z      P>|z|      [0.025      0.975]
---------------------------------------------------------------------------------
const            -3.5205      0.078    -45.421      0.000      -3.672      -3.369
inc_late         -0.3619      0.326     -1.108      0.268      -1.002       0.278
inc_lunch        -0.1145      0.038     -2.984      0.003      -0.190      -0.039
inc_isolated     -0.0583      0.025     -2.368      0.018      -0.107      -0.010
inc_days          0.1435      0.063      2.262      0.024       0.019       0.268
inc_wednesday     0.0080      0.188      0.043      0.966      -0.360       0.376
inc_travel        0.0055      0.001      7.887      0.000       0.004       0.007
=================================================================================

Estimated coefficients (utility weights):
const           -3.520513
inc_late        -0.361856
inc_lunch       -0.114460
inc_isolated    -0.058324
inc_days         0.143538
inc_wednesday    0.007994
inc_travel       0.005477
dtype: float64

In [41]:
# After building `merged` (which contains all events with week numbers), 
# expand the data so each event row is repeated for each week it occurs.
def parse_weeks(weeks_str):
    if pd.isna(weeks_str):
        return []
    weeks = []
    for part in str(weeks_str).split(','):
        if '-' in part:
            start, end = map(int, part.split('-'))
            weeks.extend(range(start, end + 1))
        else:
            weeks.append(int(part))
    return weeks

expanded_rows = []
for _, row in merged.iterrows():
    weeks = parse_weeks(row['Weeks'])
    for w in weeks:
        new_row = row.copy()
        new_row['Week'] = w
        expanded_rows.append(new_row)
expanded_df = pd.DataFrame(expanded_rows)

# Now group by student and week to build the schedule for that week
student_weekly_travel = []
for student_id in expanded_df['AnonID'].unique():
    student_df = expanded_df[expanded_df['AnonID'] == student_id]
    weeks = student_df['Week'].unique()
    for w in weeks:
        week_df = student_df[student_df['Week'] == w]
        # Build list of events for this week: (day_num, model_hour, campus, duration)
        events = []
        for _, row in week_df.iterrows():
            events.append((row['DayNum'], row['ModelHour'], row['Campus'], row['Duration (minutes)']))
        if events:
            metrics = compute_metrics_with_travel(events)
            student_weekly_travel.append(metrics['travel'])
    # Print progress (optional)
    # if len(student_weekly_travel) % 100 == 0:
    #     print(f"Processed {len(student_weekly_travel)} weeks")

# Now we have a list of weekly travel times for all students
avg_travel = np.mean(student_weekly_travel)
max_travel = np.max(student_weekly_travel)
print(f"Average weekly travel time: {avg_travel:.2f} minutes")
print(f"Maximum weekly travel time: {max_travel:.2f} minutes")

Average weekly travel time: 168.87 minutes
Maximum weekly travel time: 660.00 minutes

In [42]:
evmr_sem1=evmr[evmr['Semester']=='Semester 1']

In [43]:
evmr_sem1['minweek']=evmr_sem1['Weeks'].apply(lambda x: min(parse_weeks(x)))
print(min(evmr_sem1['minweek']))

5

C:\Users\frequensy\AppData\Local\Temp\ipykernel_26144\1086685216.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  evmr_sem1['minweek']=evmr_sem1['Weeks'].apply(lambda x: min(parse_weeks(x)))

In [44]:
evmr_sem1[('maxweek')]=evmr_sem1['Weeks'].apply(lambda x: max(parse_weeks(x)))
print(max(evmr_sem1['maxweek']))

52

C:\Users\frequensy\AppData\Local\Temp\ipykernel_26144\1369585246.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  evmr_sem1[('maxweek')]=evmr_sem1['Weeks'].apply(lambda x: max(parse_weeks(x)))

In [45]:
evmr_sem2=evmr[evmr['Semester']=='Semester 2']

In [46]:
evmr_sem2['minweek']=evmr_sem2['Weeks'].apply(lambda x: min(parse_weeks(x)))
print(min(evmr_sem2['minweek']))

25

C:\Users\frequensy\AppData\Local\Temp\ipykernel_26144\2531507784.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  evmr_sem2['minweek']=evmr_sem2['Weeks'].apply(lambda x: min(parse_weeks(x)))

In [47]:
evmr_sem2[('maxweek')]=evmr_sem2['Weeks'].apply(lambda x: max(parse_weeks(x)))
print(max(evmr_sem2['maxweek']))

51

C:\Users\frequensy\AppData\Local\Temp\ipykernel_26144\1630798745.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  evmr_sem2[('maxweek')]=evmr_sem2['Weeks'].apply(lambda x: max(parse_weeks(x)))

In [48]:

# Collect weeks per semester
weeks_sem1 = set()
weeks_sem2 = set()

for _, row in evmr.iterrows():
    semester = row.get('Semester')
    weeks_str = row.get('Weeks')
    weeks = parse_weeks(weeks_str)
    if semester == 'Semester 1':
        weeks_sem1.update(weeks)
    elif semester == 'Semester 2':
        weeks_sem2.update(weeks)

E1 = sorted(weeks_sem1)
E2 = sorted(weeks_sem2)
E = sorted(set(E1) | set(E2))

print("Semester 1 weeks:", E1)
print("Semester 2 weeks:", E2)
print("All weeks:", E)

Semester 1 weeks: [5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 32, 33, 34, 35, 36, 37, 52]
Semester 2 weeks: [25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51]
All weeks: [5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52]

In [51]:
# After the data preparation steps (after `merged` is defined and filtered to the relevant programmes)
# -------------------------------------------------------------------
# Identify students in the five joint degrees
# -------------------------------------------------------------------
joint_programmes = ["UTMATPH", "UTBSCMATBU1F", "UTCMPMA", "UTECNMA", "UTPHIMA"]
# merged already has 'ProgBase' column (the base programme code)
joint_students = merged[merged['ProgBase'].isin(joint_programmes)]

# -------------------------------------------------------------------
# Count distinct student‑module pairs for mathematics courses
# -------------------------------------------------------------------
# Define a mathematics course as one whose ModCode starts with "MATH"
# (you can adjust this condition if needed)
math_courses = joint_students[joint_students['ModCode'].str.startswith('MATH', na=False)]

# Count per module (distinct student-module pairs)
course_counts = math_courses.groupby('ModCode')['AnonID'].nunique().sort_values(ascending=False)
top8_courses = course_counts.head(8).index.tolist()
print("Top 8 most taken mathematics courses:")
for i, course in enumerate(top8_courses, 1):
    print(f"{i}. {course} (taken by {course_counts[course]} students)")

# -------------------------------------------------------------------
# For each top course, list which joint degrees took it
# -------------------------------------------------------------------
degree_course_map = {}
for course in top8_courses:
    # Students who took this course
    students_with_course = math_courses[math_courses['ModCode'] == course]['AnonID'].unique()
    # Get programmes of those students (distinct)
    prog_list = math_courses[math_courses['AnonID'].isin(students_with_course)]['ProgBase'].unique()
    degree_course_map[course] = prog_list

print("\nWhich degrees took each top course:")
for course, degs in degree_course_map.items():
    deg_names = []
    for d in degs:
        if d == "UTMATPH":
            deg_names.append("Maths & Physics")
        elif d == "UTBSCMATBU1F":
            deg_names.append("Maths & Business")
        elif d == "UTCMPMA":
            deg_names.append("CS & Maths")
        elif d == "UTECNMA":
            deg_names.append("Economics & Maths")
        elif d == "UTPHIMA":
            deg_names.append("Philosophy & Maths")
    print(f"{course}: {', '.join(deg_names)}")

Top 8 most taken mathematics courses:
1. MATH08064 (taken by 100 students)
2. MATH08063 (taken by 92 students)
3. MATH08066 (taken by 78 students)
4. MATH08059 (taken by 68 students)
5. MATH08058 (taken by 62 students)
6. MATH08057 (taken by 61 students)
7. MATH10067 (taken by 48 students)
8. MATH10066 (taken by 43 students)

Which degrees took each top course:
MATH08064: Maths & Business, Economics & Maths, CS & Maths, Philosophy & Maths, Maths & Physics
MATH08063: Maths & Business, Economics & Maths, Philosophy & Maths, Maths & Physics, CS & Maths
MATH08066: Economics & Maths, Maths & Physics, CS & Maths, Maths & Business
MATH08059: Philosophy & Maths, Maths & Physics, Economics & Maths, CS & Maths, Maths & Business
MATH08058: Philosophy & Maths, CS & Maths, Maths & Physics, Economics & Maths, Maths & Business
MATH08057: Philosophy & Maths, CS & Maths, Maths & Physics, Economics & Maths, Maths & Business
MATH10067: CS & Maths, Philosophy & Maths, Maths & Physics, Maths & Business, Economics & Maths
MATH10066: Maths & Business, CS & Maths, Philosophy & Maths, Maths & Physics, Economics & Maths

In [56]:
# Bring in Programme Year from DPT (using the base programme code)
# First, get unique programme-year combinations from filtered_dpt
prog_year = filtered_dpt[['Programme Code', 'Programme Year']].drop_duplicates()
# Merge into merged on ProgBase (which matches Programme Code)
merged = merged.merge(prog_year, left_on='ProgBase', right_on='Programme Code', how='left')
# Drop the extra column if needed
merged.drop(columns='Programme Code', inplace=True, errors='ignore')

In [57]:
# After the data preparation steps (including the merge above)
joint_programmes = ["UTMATPH", "UTBSCMATBU1F", "UTCMPMA", "UTECNMA", "UTPHIMA"]
prog_names = {
    "UTMATPH": "Maths & Physics",
    "UTBSCMATBU1F": "Maths & Business",
    "UTCMPMA": "CS & Maths",
    "UTECNMA": "Economics & Maths",
    "UTPHIMA": "Philosophy & Maths"
}

# Filter to joint programmes, math courses, and years 3 & 4
joint_math = merged[
    (merged['ProgBase'].isin(joint_programmes)) &
    (merged['ModCode'].str.startswith('MATH', na=False)) &
    (merged['Programme Year'].isin([3, 4]))
].copy()

# Group by programme, year, module, count distinct students
course_counts = joint_math.groupby(['ProgBase', 'Programme Year', 'ModCode'])['AnonID'].nunique().reset_index()
course_counts.columns = ['ProgBase', 'Year', 'ModCode', 'StudentCount']

# Sort and get top 4 per group
top4_per_group = course_counts.groupby(['ProgBase', 'Year']).apply(
    lambda x: x.nlargest(4, 'StudentCount')
).reset_index(drop=True)

print("Top 4 mathematics courses per joint degree and year:")
for (prog, year), group in top4_per_group.groupby(['ProgBase', 'Year']):
    print(f"\n{prog_names[prog]} - Year {year}:")
    for _, row in group.iterrows():
        print(f"  {row['ModCode']}: taken by {row['StudentCount']} students")

Top 4 mathematics courses per joint degree and year:

Maths & Business - Year 3.0:
  MATH10065: taken by 15 students
  MATH08064: taken by 10 students
  MATH08063: taken by 9 students
  MATH08051: taken by 8 students

Maths & Business - Year 4.0:
  MATH10065: taken by 15 students
  MATH08064: taken by 10 students
  MATH08063: taken by 9 students
  MATH08051: taken by 8 students

CS & Maths - Year 3.0:
  MATH08064: taken by 31 students
  MATH08063: taken by 29 students
  MATH08066: taken by 29 students
  MATH08059: taken by 25 students

CS & Maths - Year 4.0:
  MATH08064: taken by 31 students
  MATH08063: taken by 29 students
  MATH08066: taken by 29 students
  MATH08059: taken by 25 students

Economics & Maths - Year 3.0:
  MATH08051: taken by 28 students
  MATH08064: taken by 27 students
  MATH08063: taken by 26 students
  MATH08066: taken by 26 students

Economics & Maths - Year 4.0:
  MATH08051: taken by 28 students
  MATH08064: taken by 27 students
  MATH08063: taken by 26 students
  MATH08066: taken by 26 students

Maths & Physics - Year 3.0:
  MATH08066: taken by 15 students
  MATH08064: taken by 14 students
  MATH08058: taken by 13 students
  MATH08059: taken by 13 students

Maths & Physics - Year 4.0:
  MATH08066: taken by 15 students
  MATH08064: taken by 14 students
  MATH08058: taken by 13 students
  MATH08059: taken by 13 students

Philosophy & Maths - Year 3.0:
  MATH08063: taken by 18 students
  MATH08064: taken by 18 students
  MATH08059: taken by 12 students
  MATH10067: taken by 12 students

Philosophy & Maths - Year 4.0:
  MATH08063: taken by 18 students
  MATH08064: taken by 18 students
  MATH08059: taken by 12 students
  MATH10067: taken by 12 students

C:\Users\frequensy\AppData\Local\Temp\ipykernel_26144\4200660879.py:23: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  top4_per_group = course_counts.groupby(['ProgBase', 'Year']).apply(